#!/bin/bash
# Pre-commit hook: Ensure static/img/statistics/ is not accidentally committed
#
# Purpose:
#   Prevents regression: no one should commit runtime-generated statistics files to Git
#   (they're removed as of Jan 2026)
#
# Installation:
#   cp scripts/hooks/pre-commit-check-statistics.sh .git/hooks/pre-commit
#   chmod +x .git/hooks/pre-commit
#
# Usage:
#   Runs automatically before each commit.
#   Will fail the commit if static/img/statistics/* files are staged.

set -e

# Check if any PNG or JSON files in static/img/statistics/ are staged
STAGED_STATS_FILES=$(git diff --cached --name-only | grep -E '^static/img/statistics/(viz_.*\.png|corpus_stats\.json)$' || true)

if [ -n "$STAGED_STATS_FILES" ]; then
    echo "❌ COMMIT BLOCKED: Runtime statistics files detected in staging area!"
    echo ""
    echo "The following files should NOT be committed to Git:"
    echo "$STAGED_STATS_FILES"
    echo ""
    echo "Statistics are runtime-only, generated by:"
    echo "  LOKAL/_0_json/05_publish_corpus_statistics.py"
    echo ""
    echo "They should be deployed via:"
    echo "  LOKAL/_2_deploy/deploy_data.ps1"
    echo ""
    echo "For context, see:"
    echo "  docs/operations/legacy_static_statistics.md"
    echo ""
    echo "To fix: Run 'git reset HEAD static/img/statistics/*' to unstage"
    exit 1
fi

exit 0
